import marimo

__generated_with = "0.23.16"
app = marimo.App(
    width="medium",
    app_title="MPC Out-of-Distribution Support Investigation",
)


@app.cell
def _():
    import importlib
    import sys
    from glob import glob
    from pathlib import Path

    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np
    import yaml

    import neuro.ood

    importlib.reload(neuro.ood)

    from neuro.config import StftGeometry
    from neuro.ood import (
        OODIndex,
        binned_prediction_error,
        evaluate_prediction_errors,
        extract_mpc_rollout_queries,
        extract_run_clinical_metrics,
        extract_state_action_pairs,
        horizon_statistics,
        print_ood_report,
        select_ood_candidate_states,
        simulate_ras_branch,
    )
    from neuro.predictor.data import frame_aligned_controls, load_trajectory, reduce_trajectory_to_frames
    from neuro.predictor.inference import InferencePredictor

    return (
        InferencePredictor,
        OODIndex,
        Path,
        StftGeometry,
        binned_prediction_error,
        evaluate_prediction_errors,
        extract_mpc_rollout_queries,
        extract_run_clinical_metrics,
        extract_state_action_pairs,
        frame_aligned_controls,
        glob,
        horizon_statistics,
        load_trajectory,
        mo,
        np,
        plt,
        print_ood_report,
        reduce_trajectory_to_frames,
        select_ood_candidate_states,
        simulate_ras_branch,
        sys,
        yaml,
    )


@app.cell
def _(mo):
    mo.md(r"""
    # 🎯 Detecting Distribution Shift for Learned Dynamics in MPC

    ## 1. Theoretical Foundations & Problem Formulation

    A learned surrogate dynamics model approximates the transition mapping:
    $$x_{t+1} = f_\theta(x_t, u_t)$$
    where $x_t \in \mathbb{R}^{n_x}$ represents the system state (here, structured time-frequency Observable Frames),
    and $u_t \in \mathbb{R}^m$ is the applied control current.

    ### Why State-Action Support Matters
    The training dataset is generated by a behavior policy inducing an empirical joint distribution:
    $$p_\text{train}(x, u) = p_\text{train}(x) \, p_\text{train}(u \mid x)$$
    Even when Random Amplitude Schedule (RAS) excitation spans its admissible control bounds $[-u_\max, u_\max]$,
    certain joint state-action configurations $(x, u)$ may occur rarely or not at all.

    During closed-loop model predictive control (MPC), the optimizer evaluates candidate control sequences:
    $$U = (u_t, u_{t+1}, \dots, u_{t+H-1})$$
    and recursively unrolls predictions:
    $$\hat{x}_{t+k+1} = f_\theta(\hat{x}_{t+k}, u_{t+k}), \quad k = 0, \dots, H-1$$

    ### The Central Question
    > **Are the state-action pairs $(x, u)$ queried by MPC similar to those observed during training?**

    If the optimizer drives the dynamics model into unsupported regions, the model may output unphysical hallucinations.
    The controller may exploit these errors to artificially minimize its cost function, leading to catastrophic failure
    when the selected control is applied to the real plant.
    """)
    return


@app.cell
def _(Path, glob, mo, sys):
    # Discover available closed-loop runs across all model families
    run_paths = [
        Path(p)
        for p in sorted(
            glob("artifacts/canonical_predictors_comparison/1_observable_mlp/runs/*")
            + glob("artifacts/canonical_predictors_comparison/2_waveform_mlp/runs/*")
            + glob("artifacts/canonical_predictors_comparison/3_observable_dmd/runs/*")
        )
        if Path(p).is_dir()
    ]

    # Group runs by model architecture
    model_runs: dict[str, list[Path]] = {}
    for rp in run_paths:
        m_name = rp.name.rsplit("_s", 1)[0]
        model_runs.setdefault(m_name, []).append(rp)

    filter_options = {
        f"All Architectures ({len(run_paths)} runs)": "all",
        **{f"{m} ({len(r_list)} runs)": m for m, r_list in model_runs.items()},
    }

    # Only parse sys.argv when executed directly via Python CLI (outside interactive notebook)
    cli_model = None
    cli_run = None
    cli_k = None
    cli_trajs = None
    cli_rep = None
    if not mo.running_in_notebook():

        def _cli_val(flag: str) -> str | None:
            for _i, _a in enumerate(sys.argv[:-1]):
                if _a == flag:
                    return sys.argv[_i + 1]
                if _a.startswith(f"{flag}="):
                    return _a.split("=", 1)[1]
            return None

        cli_model = _cli_val("--model")
        cli_run = _cli_val("--run")
        cli_k = _cli_val("--k")
        cli_trajs = _cli_val("--n-trajs")
        cli_rep = _cli_val("--rep")

        # If --run was specified without --model, infer model from run name
        if cli_run and not cli_model:
            run_name = Path(cli_run).name
            cli_model = run_name.rsplit("_s", 1)[0]

    default_filter_key = next(iter(filter_options))
    if cli_model:
        cli_model_name = Path(cli_model).name
        for label, val in filter_options.items():
            if val == cli_model_name or label.startswith(cli_model_name):
                default_filter_key = label
                break

    architecture_filter = mo.ui.dropdown(
        options=filter_options,
        value=default_filter_key,
        label="Filter by Architecture",
    )

    k_slider = mo.ui.slider(
        start=5,
        stop=50,
        step=5,
        value=int(cli_k) if cli_k and cli_k.isdigit() else 10,
        label="Nearest Neighbors K",
    )

    n_trajs_slider = mo.ui.slider(
        start=10,
        stop=50,
        step=10,
        value=int(cli_trajs) if cli_trajs and cli_trajs.isdigit() else 20,
        label="Training Reference Trajectories",
    )

    rep_options = {
        "Predictor-Native History [y_hist, u_hist, u]": "native",
        "Instantaneous Reduced Diagnostic [y, u]": "instant",
    }
    default_rep_key = "Predictor-Native History [y_hist, u_hist, u]"
    if cli_rep in ("0", "instant", "instantaneous"):
        default_rep_key = "Instantaneous Reduced Diagnostic [y, u]"

    rep_select = mo.ui.dropdown(
        options=rep_options,
        value=default_rep_key,
        label="State-Action Representation",
    )
    return architecture_filter, cli_run, k_slider, n_trajs_slider, rep_select


@app.cell
def _(
    Path,
    architecture_filter,
    cli_run,
    glob,
    k_slider,
    mo,
    n_trajs_slider,
    rep_select,
):
    # Filter available closed-loop runs based on selected architecture
    sel_model = architecture_filter.value
    if sel_model and sel_model != "all":
        run_dirs = sorted(glob(f"artifacts/canonical_predictors_comparison/*/runs/{sel_model}_s*"))
    else:
        run_dirs = sorted(glob("artifacts/canonical_predictors_comparison/*/runs/*"))

    if not run_dirs:
        run_dirs = sorted(glob("artifacts/canonical_predictors_comparison/*/runs/*"))

    run_options = {Path(p).name: str(p) for p in run_dirs} if run_dirs else {"None": ""}

    default_run_key = next(iter(run_options))
    if cli_run:
        cli_run_name = Path(cli_run).name
        if cli_run_name in run_options:
            default_run_key = cli_run_name
        elif cli_run in run_options.values():
            default_run_key = next(k for k, v in run_options.items() if v == cli_run)

    run_select = mo.ui.dropdown(
        options=run_options,
        value=default_run_key,
        label="Closed-Loop MPC Run",
    )

    custom_run_input = mo.ui.text(
        value=cli_run or "",
        label="Or Enter Custom Run Directory Path (Overrides dropdown selection)",
        placeholder="e.g. artifacts/canonical_predictors_comparison/1_observable_mlp/runs/fast_linear_kw5_s7000",
        full_width=True,
    )

    custom_train_data_input = mo.ui.text(
        value="",
        label="Training Dataset Directory (Optional override; auto-detected from model if blank)",
        placeholder="e.g. data/experiment_excited_60ms/train",
        full_width=True,
    )

    mo.vstack(
        [
            mo.md("### ⚙️ Experiment Run Selection"),
            mo.hstack([architecture_filter, run_select], justify="start"),
            custom_run_input,
            custom_train_data_input,
            mo.hstack([k_slider, n_trajs_slider, rep_select], justify="start"),
        ]
    )
    return custom_run_input, custom_train_data_input, run_select


@app.cell
def _(
    InferencePredictor,
    OODIndex,
    Path,
    StftGeometry,
    custom_run_input,
    custom_train_data_input,
    extract_run_clinical_metrics,
    extract_state_action_pairs,
    frame_aligned_controls,
    load_trajectory,
    mo,
    n_trajs_slider,
    np,
    reduce_trajectory_to_frames,
    rep_select,
    run_select,
    yaml,
):
    # Resolve run directory: custom path override takes precedence over dropdown if specified
    custom_raw = custom_run_input.value.strip()
    run_dir = Path(custom_raw) if custom_raw else Path(run_select.value)

    cfg_file = run_dir / "config.yaml"
    if not cfg_file.exists():
        # Helpful error check if the user accidentally passed a model artifact path instead of a run
        if (run_dir / "weights.pt").exists() or (run_dir / "model.npz").exists() or Path(f"{run_dir}.npz").exists():
            _err_msg = (
                f"Path '{run_dir}' is a predictor model artifact, not a closed-loop MPC run.\n"
                "Please specify a closed-loop MPC run directory containing 'config.yaml' and 'log.npz'."
            )
            raise ValueError(_err_msg)
        _missing_cfg = f"Run configuration not found at {cfg_file}"
        raise FileNotFoundError(_missing_cfg)

    with cfg_file.open(encoding="utf-8") as _f:
        run_cfg = yaml.safe_load(_f)

    # Automatically load the exact predictor model configured and executed in this closed-loop run
    model_path = run_cfg.get("controller", {}).get("problem", {}).get("artifact")
    if not model_path:
        _missing_art = f"No predictor artifact specified in {cfg_file}"
        raise ValueError(_missing_art)

    model = InferencePredictor.load(model_path)
    if hasattr(model, "geometry"):
        geom = getattr(
            model,
            "geometry",
            StftGeometry(
                n_segment=25,
                n_hop=3,
                band_hz=[1.0, 25.0],
                n_bin_pool=1,
                kernel="linear",
                kernel_width=5,
            ),
        )
        geom_desc = str(geom)
    else:
        geom = None
        geom_desc = f"Raw Waveform (Sample Grid, {model.p} channels, dt={model.dt}s)"
    model_display_name = Path(model_path).parent.name

    # Extract closed-loop clinical efficacy and solver runtime metrics
    try:
        clinical_metrics = extract_run_clinical_metrics(run_dir)
    except (OSError, ValueError, KeyError):
        clinical_metrics = {}

    # Auto-detect training dataset path from predictor configuration, or use UI override / fallbacks
    detected_data_dir = "data/experiment_excited_60ms/train"
    model_dir = Path(model_path).parent
    for cand_yaml in model_dir.glob("*.yaml"):
        try:
            with cand_yaml.open(encoding="utf-8") as f_y:
                y_data = yaml.safe_load(f_y)
                if isinstance(y_data, dict) and "simulation" in y_data and "data_path" in y_data["simulation"]:
                    detected_data_dir = str(y_data["simulation"]["data_path"])
                    break
        except (OSError, yaml.YAMLError, KeyError):
            pass

    custom_train_raw = custom_train_data_input.value.strip()
    resolved_train_dir = Path(custom_train_raw or detected_data_dir)
    train_files = sorted(resolved_train_dir.glob("*.npz"))[: n_trajs_slider.value]
    if not train_files:
        for fallback in [
            Path("data/experiment_excited_long/train"),
            Path("data/experiment_excited_60ms/train"),
            Path("data/experiment_excited_100ms/train"),
        ]:
            if fallback.exists() and list(fallback.glob("*.npz")):
                resolved_train_dir = fallback
                train_files = sorted(resolved_train_dir.glob("*.npz"))[: n_trajs_slider.value]
                break

    if not train_files:
        _err_msg = (
            f"No training trajectory files (.npz) found in '{resolved_train_dir}'.\n"
            "Please specify a valid training dataset directory via the UI text box."
        )
        raise FileNotFoundError(_err_msg)

    # Load training trajectories to establish reference and calibration partitions
    trajs: list[tuple[np.ndarray, np.ndarray]] = []
    fs = 50.0  # Decimated sampling rate

    for tf in train_files:
        u_raw, y_raw = load_trajectory(tf, None, downsample=200, dt=0.0001)
        if geom is not None:
            y_frames = reduce_trajectory_to_frames(y_raw, geom, fs=fs)
            if y_frames.ndim > 2:
                y_frames = y_frames.reshape(len(y_frames), -1)
            u_frames = frame_aligned_controls(u_raw, geom, fs=fs)[: len(y_frames)]
        else:
            y_frames = y_raw
            u_frames = u_raw
        trajs.append((u_frames, y_frames))

    # Trajectory-level split: 80% reference, 20% ID calibration
    n_ref = max(1, int(len(trajs) * 0.8))
    ref_trajs = trajs[:n_ref]
    cal_trajs = trajs[n_ref:]

    if rep_select.value == "instant":
        n_y_val = 1
        n_u_val = 0
        rep_desc = "Instantaneous Diagnostic [y, u]"
    else:
        n_y_val = int(getattr(model, "n_y", 1))
        n_u_val = int(getattr(model, "n_u", 0))
        rep_desc = f"Predictor-Native History (n_y={n_y_val}, n_u={n_u_val})"

    z_ref, _ = extract_state_action_pairs(ref_trajs, n_y=n_y_val, n_u=n_u_val)
    z_cal, _ = extract_state_action_pairs(cal_trajs, n_y=n_y_val, n_u=n_u_val)

    ood_index = OODIndex.fit(z_ref, z_cal, k=10)
    cv = ood_index.coefficient_of_variation()

    source_tag = f"*(Custom path override: `{custom_raw}`)*" if custom_raw else "*(Dropdown Selection)*"

    mo.md(f"""
    ### 📐 Active Closed-Loop MPC Run & Predictor Model {source_tag}
    - **Active Run**: `{run_dir.name}` (`{run_dir}`)
    - **Configured Predictor**: `{model_display_name}` (`{model_path}`)
    - **Model Architecture**: `{model.__class__.__name__}` (observable dimension $p = {model.p}$, $n_y = {model.n_y}$, $n_u = {model.n_u}$)
    - **State Representation**: `{geom_desc}`
    - **OOD History Mode**: `{rep_desc}`
    - **Training Dataset Source**: `{resolved_train_dir}` ({len(train_files)} files loaded)
    - **Normalization**: Standardized using reference statistics $\\mu_j$ and $\\sigma_j$.
    - **Reference Set**: `{ood_index.reference_count:,}` standardized vectors $\\mathcal{{Z}}_\\text{{ref}}$ spanning {len(ref_trajs)} trajectories.
    - **Held-out ID Calibration Set**: `{ood_index.calibration_count:,}` standardized vectors from {len(cal_trajs)} trajectories.
    - **Dimension**: $D = {ood_index.dimension}$ features.
    - **Dispersion ($CV$)**: `{cv:.4f}`.
    """)
    return (
        cal_trajs,
        clinical_metrics,
        geom,
        model,
        n_u_val,
        n_y_val,
        ood_index,
        resolved_train_dir,
        run_dir,
    )


@app.cell
def _(clinical_metrics, mo, np, plt, run_dir):
    _clin = clinical_metrics if isinstance(clinical_metrics, dict) else {}
    _burden = _clin.get("seizure_burden")
    _burden_pct = _burden * 100.0 if _burden is not None else float("nan")
    _n_seize = _clin.get("n_seizing_final", float("nan"))
    _charge = _clin.get("delivered_charge", float("nan"))
    _amp = _clin.get("mean_amplitude", float("nan"))
    _amp_pct = _amp * 100.0 if not np.isnan(_amp) else float("nan")
    _kirch = _clin.get("kirchhoff_max", float("nan"))
    _p95_s = _clin.get("solve_time_p95_s", float("nan"))
    _rt_factor = _clin.get("realtime_factor", float("nan"))
    _succ_rate = _clin.get("solve_success_rate", float("nan"))

    if not np.isnan(_burden_pct):
        if _burden_pct < 10.0:
            _status_badge = "🟢 **EXCELLENT SUPPRESSION** (Seizure Burden < 10%)"
        elif _burden_pct < 25.0:
            _status_badge = "🟡 **PARTIAL SUPPRESSION** (10% ≤ Seizure Burden < 25%)"
        else:
            _status_badge = "🔴 **POOR SUPPRESSION / UNCONTAINED SPREAD** (Seizure Burden ≥ 25%)"
    else:
        _status_badge = "⚪ **EVALUATION DATA PENDING**"

    _ez_rec = int(_clin.get("ez_recruited", 0))
    _pz_rec = int(_clin.get("pz_recruited", 0))
    _h_rec = int(_clin.get("healthy_recruited", 0))

    _summary_md = f"""
    ---
    ## 🏥 Closed-Loop Clinical Efficacy & Control Performance

    ### Primary Clinical Outcome: {_status_badge}

    | Clinical / Control Dimension | Observed Value | Clinical Interpretation & Reference |
    | :--- | :---: | :--- |
    | **Seizure Burden** | **`{_burden_pct:.2f}%`** | Continuous time-averaged network fraction seizing (Uncontrolled baseline: ~12.4%). |
    | **Final Seizing Regions** | **`{int(_n_seize) if not np.isnan(_n_seize) else "N/A"} / 76`** | Active nodes at $t = t_\\text{{end}}$ (EZ: **{_ez_rec}/3**, PZ: **{_pz_rec}/2**, Healthy: **{_h_rec}/71**). |
    | **Total Delivered Charge** | **`{_charge:.3f} mA·s`** | Net stimulation energy $\\int \\sum |u_i(t)| dt$ delivered through scalp electrodes. |
    | **Mean Control Amplitude** | **`{_amp_pct:.2f}% of u_max`** | Control Budget utilization ($|u_i| \\le 2.0\\text{{ mA}}$). |
    | **Kirchhoff Law Residual** | **`{_kirch:.2e} mA`** | Maximum instantaneous net sum $\\max_t |\\sum_i u_i(t)|$ (verifies zero-sum charge balance). |
    | **Solver P95 Solve Time** | **`{_p95_s:.3f}s`** (rt factor: `{_rt_factor:.1f}x`) | Decision-time optimization latency (Realtime capability threshold: $\\le 1.0\\text{{x}}$). |
    | **Solve Success Rate** | **`{_succ_rate * 100:.1f}%`** | Fraction of decision steps converged without numerical failure. |
    """

    _log_file = run_dir / "log.npz"
    _fig_clin = None
    if _log_file.exists():
        with np.load(_log_file) as _data:
            if (
                "dynamics.lfp" in _data
                and "dynamics.t" in _data
                and "controller.u" in _data
                and "controller.t" in _data
            ):
                # Decimate LFP by 100 for fast high-resolution interactive rendering
                _decim = 100
                _lfp = np.asarray(_data["dynamics.lfp"][::_decim], dtype=np.float64)
                _t_lfp = np.asarray(_data["dynamics.t"][::_decim], dtype=np.float64)
                _u = np.asarray(_data["controller.u"], dtype=np.float64)
                _t_u = np.asarray(_data["controller.t"], dtype=np.float64)
                _warm = (
                    _data["controller.warmup"].astype(bool)
                    if "controller.warmup" in _data
                    else np.zeros(len(_t_u), dtype=bool)
                )
                _t_warmup = float(_t_u[_warm][-1]) if np.any(_warm) else 0.0

                _fig_clin, (_ax_lfp, _ax_u) = plt.subplots(
                    2, 1, figsize=(10, 5.2), sharex=True, gridspec_kw={"height_ratios": [2.2, 1.0]}
                )

                _ez_nodes = [47, 62, 40]
                _pz_nodes = [69, 72]
                _healthy_nodes = [i for i in range(_lfp.shape[1]) if i not in _ez_nodes and i not in _pz_nodes]

                _ax_lfp.plot(_t_lfp, _lfp[:, _healthy_nodes], color="#94a3b8", alpha=0.35, lw=0.7)
                _ax_lfp.plot(
                    _t_lfp, _lfp[:, _pz_nodes], color="#f59e0b", alpha=0.85, lw=1.3, label="Propagation Zone (PZ)"
                )
                _ax_lfp.plot(
                    _t_lfp, _lfp[:, _ez_nodes], color="#ef4444", alpha=0.95, lw=1.5, label="Epileptogenic Zone (EZ)"
                )
                _ax_lfp.axhline(5.0, color="#dc2626", linestyle="--", lw=1.5, label="Seizure Threshold (5.0 mV)")
                if _t_warmup > 0:
                    _ax_lfp.axvspan(
                        0, _t_warmup, color="#e2e8f0", alpha=0.5, label=f"Warm-up Period ({_t_warmup:.2f}s)"
                    )

                _ax_lfp.set_ylabel("LFP Amplitude (mV)")
                _ax_lfp.set_title("Ground-Truth Plant Electrophysiology & Seizure Propagation")
                _ax_lfp.grid(visible=True, linestyle=":", alpha=0.5)
                _ax_lfp.legend(loc="upper right", frameon=True, fontsize=8)

                _colors = ["#0284c7", "#10b981", "#8b5cf6"]
                for _ch in range(_u.shape[1]):
                    _ax_u.step(
                        _t_u,
                        _u[:, _ch],
                        where="post",
                        color=_colors[_ch % len(_colors)],
                        lw=1.4,
                        label=f"Electrode {_ch + 1}",
                    )
                _ax_u.axhline(2.0, color="#64748b", linestyle=":", lw=1.0)
                _ax_u.axhline(-2.0, color="#64748b", linestyle=":", lw=1.0)
                if _t_warmup > 0:
                    _ax_u.axvspan(0, _t_warmup, color="#e2e8f0", alpha=0.5)

                _ax_u.set_ylabel("Current u (mA)")
                _ax_u.set_xlabel("Simulation Time (s)")
                _ax_u.set_title("Applied Control Current (Kirchhoff-Constrained Scalp Electrodes)")
                _ax_u.grid(visible=True, linestyle=":", alpha=0.5)
                _ax_u.legend(loc="upper right", frameon=True, fontsize=8)
                plt.tight_layout()

    _clin_elements = [mo.md(_summary_md)]
    if _fig_clin is not None:
        _clin_elements.append(mo.as_html(_fig_clin))
    mo.vstack(_clin_elements)
    return


@app.cell
def _(mo):
    mo.md(r"""
    ---
    ## 2. Criteria 1 & 6: Distance Distribution & Dimensionality Check

    ### Mathematical Formulation
    For any state-action query $z = [x, u]$, its $K$-nearest-neighbor distance relative to the training reference set $\mathcal{Z}_\text{ref}$ is:
    $$d_K(z) = \frac{1}{K} \sum_{i \in \mathcal{N}_K(z)} \|\tilde{z} - \tilde{z}_i\|_2$$
    Using the held-out in-distribution (ID) calibration set $\{d_K(z_i^\text{cal})\}_{i=1}^{N_\text{cal}}$, we define the empirical cumulative distribution function $\hat{F}_\text{ID}(d)$.
    The raw distance is mapped to an **ID Percentile**:
    $$q(z) = \hat{F}_\text{ID}(d_K(z)) \in [0, 1]$$

    ### Criterion 6: Check Distance Concentration
    In high-dimensional spaces ($D \approx 750$), distances can concentrate ($d_\max / d_\min \to 1$).
    We evaluate the **Coefficient of Variation**:
    $$CV = \frac{\operatorname{std}(d_K^\text{cal})}{\operatorname{mean}(d_K^\text{cal})}$$
    - **Desired ("Good")**: $CV > 0.05$ (meaningful relative spread across calibration points).
    - **Failure Mode**: $CV \to 0$ (all points are equidistant; metric collapses).

    ### Criterion 1: Does MPC Shift Off-Distribution?
    - **Desired ("Good")**: MPC queries fall predominantly within the in-distribution support zone ($q < 0.95$), overlapping with the ID calibration density.
    - **Concerning ("Shifted")**: MPC density shifts strongly to the right into the tail ($q > 0.95$ and $q > 0.99$).
    """)
    return


@app.cell
def _(
    extract_mpc_rollout_queries,
    horizon_statistics,
    k_slider,
    mo,
    model,
    n_u_val,
    n_y_val,
    np,
    ood_index,
    plt,
    run_dir,
):
    active_k = k_slider.value
    log_file = run_dir / "log.npz"

    if not log_file.exists():
        _missing_log = f"Log file not found at {log_file}"
        raise FileNotFoundError(_missing_log)

    mpc_queries, planned_u, _valid_decisions = extract_mpc_rollout_queries(
        log_file, n_y=n_y_val, n_u=n_u_val, model=model
    )
    n_decisions, horizon, dim = mpc_queries.shape

    flat_queries = mpc_queries.reshape(-1, dim)
    mpc_distances_flat = ood_index.compute_distances(flat_queries)
    mpc_percentiles_flat = ood_index.percentiles(mpc_distances_flat)

    mpc_distances = mpc_distances_flat.reshape(n_decisions, horizon)
    mpc_percentiles = mpc_percentiles_flat.reshape(n_decisions, horizon)

    h_stats = horizon_statistics(mpc_percentiles, mpc_distances)
    cal_distances = ood_index.id_cal_distances
    cv_score = ood_index.coefficient_of_variation()

    # Threshold values from ID calibration
    d_id_median = float(np.median(cal_distances))
    d_id_95 = float(np.quantile(cal_distances, 0.95))
    d_id_99 = float(np.quantile(cal_distances, 0.99))

    # Realized knot 0 vs Planned lookahead knots
    d_k0 = mpc_distances[:, 0]
    d_kfut = mpc_distances[:, 1:].flatten() if horizon > 1 else np.empty(0, dtype=np.float64)

    # Figure: Criterion 1 & Criterion 6 (Dual-panel: Near-manifold focus + Full dynamic range)
    fig1, (ax1_zoom, ax1_log) = plt.subplots(1, 2, figsize=(13, 5.0))

    d_max_mpc = float(np.max(mpc_distances_flat))
    d_max_cal = float(np.max(cal_distances))
    is_extreme_drift = d_max_mpc > 2.5 * d_id_99

    # --- Left Panel: Near-Manifold Support Focus (Linear Scale) ---
    x_max_zoom = (
        float(max(2.5 * d_id_99, 1.25 * d_max_cal)) if is_extreme_drift else float(max(d_max_mpc, d_max_cal) * 1.05)
    )
    min_d_zoom = float(max(0.0, min(cal_distances.min(), d_k0.min()) * 0.90))

    ax1_zoom.axvspan(0, d_id_95, color="#2ca02c", alpha=0.10, label="Desired (q < 0.95)")
    ax1_zoom.axvspan(d_id_95, d_id_99, color="#ff7f0e", alpha=0.12, label="Marginal (0.95 <= q < 0.99)")
    ax1_zoom.axvspan(d_id_99, x_max_zoom, color="#d62728", alpha=0.12, label="Unsupported (q >= 0.99)")

    bins_zoom = np.linspace(min_d_zoom, x_max_zoom, 35)
    ax1_zoom.hist(
        cal_distances,
        bins=bins_zoom,
        density=True,
        alpha=0.60,
        color="#1f77b4",
        edgecolor="none",
        label=f"ID Calibration (mean={np.mean(cal_distances):.2f})",
    )
    ax1_zoom.hist(
        d_k0,
        bins=bins_zoom,
        density=True,
        alpha=0.65,
        color="#0d9488",
        edgecolor="none",
        label=f"Realized k=0 (mean={np.mean(d_k0):.2f})",
    )
    d_kfut_in = d_kfut[d_kfut <= x_max_zoom] if len(d_kfut) > 0 else np.empty(0, dtype=np.float64)
    if len(d_kfut_in) > 0:
        ax1_zoom.hist(
            d_kfut_in,
            bins=bins_zoom,
            density=True,
            alpha=0.45,
            color="#ea580c",
            edgecolor="none",
            label=f"Planned k >= 1 ({len(d_kfut_in):,}/{len(d_kfut):,} in range)",
        )

    ax1_zoom.axvline(d_id_median, color="#2ca02c", linestyle="--", lw=1.6, label=f"Median d={d_id_median:.2f}")
    ax1_zoom.axvline(d_id_95, color="#ff7f0e", linestyle=":", lw=1.5, label=f"95% Bound ({d_id_95:.2f})")
    ax1_zoom.axvline(d_id_99, color="#d62728", linestyle=":", lw=1.5, label=f"99% Bound ({d_id_99:.2f})")

    ax1_zoom.set_xlim(min_d_zoom, x_max_zoom)
    ax1_zoom.set_xlabel(f"Standardized {active_k}-NN Distance d_{active_k}")
    ax1_zoom.set_ylabel("Probability Density")
    ax1_zoom.set_title("Near-Manifold Focus (Linear Scale)")
    ax1_zoom.legend(loc="upper right", frameon=True, fontsize=8)
    ax1_zoom.grid(visible=True, linestyle=":", alpha=0.5)

    if is_extreme_drift:
        pct_exceed = float(np.mean(d_kfut > x_max_zoom) * 100.0) if len(d_kfut) > 0 else 0.0
        ax1_zoom.text(
            0.5,
            0.92,
            f"⚠️ {pct_exceed:.1f}% planned knots exceed d={x_max_zoom:.1f}\n(Max d={d_max_mpc:.0f} → see Log-Scale panel)",
            transform=ax1_zoom.transAxes,
            ha="center",
            va="top",
            fontsize=8.0,
            bbox={"boxstyle": "round,pad=0.3", "facecolor": "#fef2f2", "edgecolor": "#ef4444", "alpha": 0.95},
        )

    # --- Right Panel: Full Multi-Scale Distribution (Log10 Distance Scale) ---
    ax1_log.set_xscale("log")
    min_d_log = float(max(1e-2, min(cal_distances.min(), mpc_distances_flat.min()) * 0.85))
    max_d_log = float(max(d_max_cal, d_max_mpc) * 1.25)
    bins_log = np.geomspace(min_d_log, max_d_log, 40)

    ax1_log.axvspan(min_d_log, d_id_95, color="#2ca02c", alpha=0.10, label="Desired (q < 0.95)")
    ax1_log.axvspan(d_id_95, d_id_99, color="#ff7f0e", alpha=0.12, label="Marginal (0.95 <= q < 0.99)")
    ax1_log.axvspan(d_id_99, max_d_log, color="#d62728", alpha=0.12, label="Unsupported (q >= 0.99)")

    ax1_log.hist(
        cal_distances,
        bins=bins_log,
        density=True,
        alpha=0.60,
        color="#1f77b4",
        edgecolor="none",
        label=f"ID Calibration (median={d_id_median:.2f})",
    )
    ax1_log.hist(
        d_k0,
        bins=bins_log,
        density=True,
        alpha=0.65,
        color="#0d9488",
        edgecolor="none",
        label=f"Realized k=0 (median={np.median(d_k0):.2f})",
    )
    if len(d_kfut) > 0:
        ax1_log.hist(
            d_kfut,
            bins=bins_log,
            density=True,
            alpha=0.45,
            color="#ea580c",
            edgecolor="none",
            label=f"Planned k >= 1 (median={np.median(d_kfut):.2f})",
        )

    ax1_log.axvline(d_id_median, color="#2ca02c", linestyle="--", lw=1.6)
    ax1_log.axvline(d_id_95, color="#ff7f0e", linestyle=":", lw=1.5)
    ax1_log.axvline(d_id_99, color="#d62728", linestyle=":", lw=1.5)

    ax1_log.set_xlim(min_d_log, max_d_log)
    ax1_log.set_xlabel(f"Standardized {active_k}-NN Distance d_{active_k} (Log Scale)")
    ax1_log.set_ylabel("Probability Density")
    ax1_log.set_title("Full Dynamic Range (Log10 Distance Scale)")
    ax1_log.legend(loc="upper right", frameon=True, fontsize=8)
    ax1_log.grid(visible=True, linestyle=":", alpha=0.5)

    plt.tight_layout()

    p95_rate = float(np.mean(mpc_percentiles_flat > 0.95) * 100.0)
    p99_rate = float(np.mean(mpc_percentiles_flat > 0.99) * 100.0)

    with np.load(log_file) as log_data:
        t_decisions = np.asarray(log_data["controller.t"], dtype=np.float64)[_valid_decisions]

    e_realized = (
        np.linalg.norm(mpc_queries[1:, 0, : model.p] - mpc_queries[:-1, 1, : model.p], axis=-1)
        if n_decisions > 1
        else np.empty(0, dtype=np.float64)
    )

    k0_p95 = float(np.mean(d_k0 > d_id_95) * 100.0)
    kfut_p95 = float(np.mean(d_kfut > d_id_95) * 100.0) if len(d_kfut) > 0 else 0.0

    eval_md = f"""
    > **Diagnostic Interpretation**:
    > - **Coefficient of Variation ($CV$)**: **{cv_score:.3f}** (Above concentration threshold of 0.05, confirming Euclidean distances in $D={dim}$ remain informative).
    > - **Empirical Distance Shift**: The MPC queries exhibit mean distance **{np.mean(mpc_distances_flat):.2f}** (Realized $k=0$: **{np.mean(d_k0):.2f}**, Planned $k \\ge 1$: **{np.mean(d_kfut):.2f}**) compared to **{np.mean(cal_distances):.2f}** for ID calibration.
    > - **Tail Support Exceedance ($P(q > 0.95)$)**: Overall **{p95_rate:.1f}%** (Realized $k=0$: **{k0_p95:.1f}%**, Planned $k \\ge 1$: **{kfut_p95:.1f}%**).
    """

    mo.vstack([mo.as_html(fig1), mo.md(eval_md)])
    return (
        active_k,
        cal_distances,
        cv_score,
        dim,
        e_realized,
        h_stats,
        horizon,
        mpc_distances_flat,
        mpc_percentiles,
        mpc_queries,
        n_decisions,
        p95_rate,
        p99_rate,
        planned_u,
        t_decisions,
    )


@app.cell
def _(mo):
    mo.md(r"""
    ---
    ## 3. Ground-Truth Realized Trajectory ($k=0$) vs. Planned Lookahead ($k \ge 1$)

    ### The Receding-Horizon Asymmetry: Plan vs. Reality
    In Model Predictive Control, an optimal control problem is solved at each decision step $t_i$:
    $$\min_{u_{0:H-1}} \sum_{k=0}^{H-1} \left( \|y_k - y_\text{target}\|_Q^2 + \|u_k\|_R^2 \right) + V_f(x_H)$$
    Crucially, **only the first action $u_0$ is ever dispatched to the plant** ($u(t_i) = u_0$). The remaining open-loop plan $u_{1:H-1}$ is discarded when the state is remeasured at $t_{i+1}$.

    ### Why Do Planned Knots ($k \ge 1$) Collapse Into an Attractor?
    - **Control Tapering**: Because control effort is penalized ($\|u_k\|_R^2$), in finite-horizon MPC without an explicit infinite-horizon cost-to-go, the optimizer shuts down control effort toward the end of the horizon ($\|u_{24}\| \to 0$).
    - **Quiescent Attractor**: Deterministically, stimulation drives the predicted state toward the nominal healthy reference ($\|y_{24}\| \to 99.8$ vs $\|y_0\| \approx 110.4$). Low control and quiescent states sit deep within the dense core of the training distribution (median $q \approx 0.000$).
    - **The Horizon Truncation / Terminal Cost Role**:
      - A **Terminal Cost** $V_f(x_H) \approx \sum_{k=H}^\infty \ell(x_k, u_k)$ approximates the infinite-horizon cost-to-go under an unconstrained stabilizing law.
      - Adding a terminal cost penalizes terminating in a state that requires ongoing effort, preventing the controller from artificially tapering control to zero ($u \to 0$) just to exploit the finite horizon boundary.
      - However, even with a terminal cost, an open-loop deterministic rollout cannot predict unmodeled stochastic neural disturbances.

    ### Why Does Realized $k=0$ Stay at the Boundary?
    The real patient / plant is continuously perturbed by stochastic biological noise and ongoing pathological drive. The system never actually reaches the peaceful terminal state. At every decision time $t_i$, the system enters again at knot $k=0$ with high state power and active stimulation ($q_0 \approx 0.60\text{--}0.70$).
    **Evaluating $k=0$ alone is the ground truth of what the physical system actually experiences.**
    """)
    return


@app.cell
def _(
    cal_distances,
    e_realized,
    mo,
    model,
    mpc_percentiles,
    mpc_queries,
    np,
    ood_index,
    planned_u,
    plt,
    t_decisions,
):
    _q0 = mpc_percentiles[:, 0]
    _q_fut = mpc_percentiles[:, 1:].reshape(-1)

    _u0_norm = np.linalg.norm(planned_u[:, 0, :], axis=-1)
    _y0_norm = np.linalg.norm(mpc_queries[:, 0, : model.p], axis=-1)

    # Figure: 2x2 multi-panel diagnostic
    _fig_real, ((_ax_ts, _ax_u), (_ax_dist, _ax_scat)) = plt.subplots(2, 2, figsize=(13, 8))

    # Panel 1: Realized q0(t) over time
    _ax_ts.plot(t_decisions, _q0, color="#1f77b4", lw=1.6, label="Realized Support $q_0(t)$")
    _ax_ts.axhline(0.95, color="#ff7f0e", linestyle="--", lw=1.4, label="95% Alert Threshold")
    _ax_ts.axhline(0.99, color="#d62728", linestyle=":", lw=1.4, label="99% Critical Alert")
    _ax_ts.axhspan(0.95, 0.99, color="#ff7f0e", alpha=0.10)
    _ax_ts.axhspan(0.99, 1.00, color="#d62728", alpha=0.15)
    _ax_ts.set_ylim(-0.02, 1.02)
    _ax_ts.set_xlabel("Closed-Loop Simulation Time (s)")
    _ax_ts.set_ylabel("Support Percentile $q(z_t)$")
    _ax_ts.set_title("Realized Trajectory (k=0) Support Over Time")
    _ax_ts.legend(loc="lower left", frameon=True, fontsize=8.5)
    _ax_ts.grid(visible=True, linestyle=":", alpha=0.5)

    # Panel 2: Applied Control & State Power
    _ax_u_twin = _ax_u.twinx()
    _p_u = _ax_u.plot(t_decisions, _u0_norm, color="#2ca02c", lw=1.5, label=r"Applied Control $\|u_t\|$")
    _p_y = _ax_u_twin.plot(
        t_decisions, _y0_norm, color="#9467bd", lw=1.3, linestyle="--", label=r"State Power $\|y_t\|$"
    )
    _ax_u.set_xlabel("Closed-Loop Simulation Time (s)")
    _ax_u.set_ylabel(r"Applied Control Norm $\|u_t\|$", color="#2ca02c")
    _ax_u_twin.set_ylabel(r"Observable Power $\|y_t\|$", color="#9467bd")
    _ax_u.set_title("Realized Actuation & Plant Dynamics")
    _lines_u = _p_u + _p_y
    _labels_u = [line.get_label() for line in _lines_u]
    _ax_u.legend(_lines_u, _labels_u, loc="upper right", frameon=True, fontsize=8.5)
    _ax_u.grid(visible=True, linestyle=":", alpha=0.5)

    # Panel 3: Distribution Comparison
    _cal_p = ood_index.percentiles(cal_distances)
    _bins_c = np.linspace(0, 1, 26)
    _ax_dist.hist(_cal_p, bins=_bins_c, density=True, alpha=0.45, color="#7f7f7f", label="ID Calibration (Uniform Ref)")
    _ax_dist.hist(
        _q_fut,
        bins=_bins_c,
        density=True,
        alpha=0.55,
        color="#2ca02c",
        label=f"Planned Rollouts k>=1 (mean={np.mean(_q_fut):.2f})",
    )
    _ax_dist.hist(
        _q0, bins=_bins_c, density=True, alpha=0.65, color="#1f77b4", label=f"Realized k=0 (mean={np.mean(_q0):.2f})"
    )
    _ax_dist.axvline(
        float(np.median(_q0)), color="#1f77b4", linestyle="--", lw=1.5, label=f"Realized Median ({np.median(_q0):.2f})"
    )
    _ax_dist.axvline(
        float(np.median(_q_fut)),
        color="#2ca02c",
        linestyle="--",
        lw=1.5,
        label=f"Planned Median ({np.median(_q_fut):.2f})",
    )
    _ax_dist.set_xlabel("Support Percentile $q$")
    _ax_dist.set_ylabel("Density")
    _ax_dist.set_title("Empirical Distribution: Realized vs. Planned")
    _ax_dist.legend(loc="upper right", frameon=True, fontsize=8)
    _ax_dist.grid(visible=True, linestyle=":", alpha=0.5)

    # Panel 4: Realized Support vs Realized 1-Step Transition Error
    if len(e_realized) > 0 and len(_q0) > len(e_realized):
        _q0_paired = _q0[: len(e_realized)]
        _ax_scat.scatter(_q0_paired, e_realized, color="#d95f02", alpha=0.6, s=24, edgecolors="none")
        _m_r, _b_r = np.polyfit(_q0_paired, e_realized, 1)
        _x_r = np.linspace(float(_q0_paired.min()), float(_q0_paired.max()), 50)
        _ax_scat.plot(
            _x_r, _m_r * _x_r + _b_r, color="#333333", lw=1.8, linestyle="--", label=f"Linear Trend (slope={_m_r:+.2f})"
        )
        _r_val = float(np.corrcoef(_q0_paired, e_realized)[0, 1])
        _ax_scat.set_title(f"Realized Transition Error vs. Support (r = {_r_val:+.3f})")
    else:
        _ax_scat.text(0.5, 0.5, "Single decision - no transition pairs", ha="center", va="center")

    _ax_scat.set_xlabel(r"Realized Support Percentile $q_0(t)$")
    _ax_scat.set_ylabel(r"1-Step Realized Error $\|y_{t+1} - \hat{y}_{t+1}\|$")
    _ax_scat.legend(loc="upper left", frameon=True, fontsize=8.5)
    _ax_scat.grid(visible=True, linestyle=":", alpha=0.5)

    plt.tight_layout()

    _real_md = f"""
    > **Realized Trajectory ($k=0$) vs. Planned Horizon ($k \\ge 1$) Assessment**:
    > - **Realized Support**: Mean $q_0 = \\mathbf{{{np.mean(_q0):.3f}}}$, Median $q_0 = \\mathbf{{{np.median(_q0):.3f}}}$ (vs. Planned $k \\ge 1$ mean $q = \\mathbf{{{np.mean(_q_fut):.3f}}}$, median $\\mathbf{{{np.median(_q_fut):.3f}}}$).
    > - **Tail Violations**: **{np.mean(_q0 > 0.95) * 100:.2f}%** of realized steps exceed the 95th percentile, and **{np.mean(_q0 > 0.99) * 100:.2f}%** exceed the 99th percentile.
    > - **Takeaway**: The controller's open-loop plan rapidly collapses into an idealized zero-control attractor ($q \\to 0$). In contrast, the real closed-loop system operates on the active boundary of the training support ($P(q > 0.95) \\approx 5\\%$, matching the in-distribution baseline).
    """

    mo.vstack([mo.as_html(_fig_real), mo.md(_real_md)])
    return


@app.cell
def _(mo):
    mo.md(r"""
    ---
    ## 4. Criteria 2 & 3: Horizon-Dependent Distribution Drift


    ### Mathematical Formulation
    Along each candidate rollout evaluated by MPC, the state-action sequence is:
    $$(\hat{x}_t, u_t), \; (\hat{x}_{t+1}, u_{t+1}), \; \dots, \; (\hat{x}_{t+H-1}, u_{t+H-1})$$
    yielding a sequence of support scores:
    $$q_0, q_1, \dots, q_{H-1}, \qquad q_k = \hat{F}_\text{ID}(d_K(\hat{x}_{t+k}, u_{t+k}))$$

    Two trajectory-level diagnostic metrics summarize the rollout:
    - **Maximum Support Violation**: $Q_{\max} = {\max}_k q_k$ (*Does the candidate rollout enter at least one severely unsupported state?*)
    - **Mean Distribution-Shift Score**: $Q_\text{mean} = \frac{1}{H} \sum_{k=0}^{H-1} q_k$ (*Is the rollout systematically far from training data?*)

    ### Theoretical Drift Hypothesis
    Because the dynamics model recursively feeds its own predictions back into its input:
    $$k \uparrow \quad\implies\quad q_k \uparrow$$
    Errors accumulate over the lookahead horizon, potentially driving long-horizon} predictions into unsupported dynamical regimes.

    ### What is Desired ("Good") vs Concerning
    - **Desired ("Good")**: A nearly flat curve staying in the safe operating zone ($q_k \le 0.50$), indicating recursive predictions do not drift off-manifold.
    - **Concerning ("Severe Compounding Drift")**: A steep upward trajectory approaching $q_k \to 1.0$, indicating that multi-step MPC lookahead is evaluating fictitious dynamics.
    """)
    return


@app.cell
def _(h_stats, horizon, mpc_percentiles, np, plt):
    fig2, (ax_h1, ax_h2) = plt.subplots(1, 2, figsize=(12, 4.5))
    h_steps = np.arange(horizon)

    # Left: Percentile trajectory across horizon
    ax_h1.axhspan(0.0, 0.50, color="#2ca02c", alpha=0.10, label="Desired Safe Zone (q <= 0.50)")
    ax_h1.axhspan(0.50, 0.95, color="#ff7f0e", alpha=0.08, label="Mild / Acceptable Drift")
    ax_h1.axhspan(0.95, 1.0, color="#d62728", alpha=0.12, label="Unsupported OOD Zone (q >= 0.95)")

    # 25th to 75th interquartile band
    q25 = np.percentile(mpc_percentiles, 25, axis=0)
    q75 = np.percentile(mpc_percentiles, 75, axis=0)
    ax_h1.fill_between(h_steps, q25, q75, color="#7570b3", alpha=0.20, label="Interquartile Range (25-75%)")

    ax_h1.plot(h_steps, h_stats["median_percentile"], color="#7570b3", lw=2.4, marker="o", ms=4, label="Median q_k")
    ax_h1.plot(h_steps, h_stats["mean_percentile"], color="#1b9e77", lw=1.8, linestyle="--", label="Mean q_k")
    ax_h1.axhline(0.50, color="#2ca02c", linestyle=":", lw=1.5, label="Desired Flat Baseline (q ≈ 0.50)")
    ax_h1.axhline(0.95, color="#ff7f0e", linestyle=":", lw=1.5, label="95% Threshold")
    ax_h1.axhline(0.99, color="#d62728", linestyle=":", lw=1.5, label="99% Threshold")

    ax_h1.set_xlabel("Prediction Horizon Step k")
    ax_h1.set_ylabel("Empirical Percentile q_k")
    ax_h1.set_ylim(-0.02, 1.03)
    ax_h1.set_title("Criterion 2: Support Percentile vs. Lookahead Horizon")
    ax_h1.legend(loc="lower right", frameon=True, fontsize=8)
    ax_h1.grid(visible=True, linestyle=":", alpha=0.5)

    # Right: Exceedance rates P(q_k > threshold)
    ax_h2.plot(h_steps, h_stats["p95_rate"] * 100.0, color="#ff7f0e", lw=2.2, marker="s", ms=4, label="P(q_k > 0.95)")
    ax_h2.plot(h_steps, h_stats["p99_rate"] * 100.0, color="#d62728", lw=2.2, marker="^", ms=4, label="P(q_k > 0.99)")
    ax_h2.axhline(5.0, color="#ff7f0e", linestyle=":", lw=1.2, label="Desired In-Distribution 95% Rate (5%)")
    ax_h2.axhline(1.0, color="#d62728", linestyle=":", lw=1.2, label="Desired In-Distribution 99% Rate (1%)")

    ax_h2.set_xlabel("Prediction Horizon Step k")
    ax_h2.set_ylabel("Violation Exceedance Rate (%)")
    ax_h2.set_title("Criterion 3: Tail Violation Frequency vs. Horizon")
    ax_h2.legend(loc="upper left", frameon=True, fontsize=8.5)
    ax_h2.grid(visible=True, linestyle=":", alpha=0.5)

    plt.tight_layout()
    return (fig2,)


@app.cell
def _(fig2, h_stats, horizon, mo, np):
    mean_q_max = float(np.mean(h_stats["q_max"]))
    mean_q_mean = float(np.mean(h_stats["q_mean"]))
    drift_delta = float(h_stats["mean_percentile"][-1] - h_stats["mean_percentile"][0])

    horizon_summary_md = f"""
    > **Horizon Diagnostics**:
    > - **Knot 0 Support ($q_0$)**: Mean = **{h_stats["mean_percentile"][0]:.3f}**, Median = **{h_stats["median_percentile"][0]:.3f}**.
    > - **Terminal Knot Support ($q_{{{horizon - 1}}}$)**: Mean = **{h_stats["mean_percentile"][-1]:.3f}**, Median = **{h_stats["median_percentile"][-1]:.3f}**.
    > - **Compounding Drift ($\\Delta q$)**: **{drift_delta:+.3f}** across the {horizon}-step horizon.
    > - **Trajectory-Level Scores**: Mean $Q_\\text{{max}} = \\mathbf{{{mean_q_max:.3f}}}$, Mean $Q_\\text{{mean}} = \\mathbf{{{mean_q_mean:.3f}}}$.
    """

    mo.vstack([mo.as_html(fig2), mo.md(horizon_summary_md)])
    return drift_delta, mean_q_max, mean_q_mean


@app.cell
def _(mo):
    mo.md(r"""
    ---
    ## 5. Criteria 4 & 5: Validation Against Ground-Truth Dynamics Error

    ### Operational Relevance of Distribution Shift
    An OOD detection score is useful if and only if it is **predictive of model unreliability**.
    If a query has a high OOD score but the model predicts with high accuracy, the score is an overly conservative false alarm.
    Conversely, if the model incurs massive prediction error in regions marked "safe", the detector suffers from catastrophic false assurance.

    ### Criterion 4: One-Step Error Validation
    We compute the one-step dynamics prediction error on held-out trajectories:
    $$e_t = \|f_\theta(x_t, u_t) - x_{t+1}\|_2$$
    alongside its calibrated support percentile $q_t = q(x_t, u_t)$.
    - **Desired ("Good")**: Monotonic escalation $q_t \uparrow \implies e_t \uparrow$. Higher percentiles must exhibit larger average prediction errors.
    - **Failure Mode**: Flat error profile across percentile bins, indicating the distance metric fails to capture dynamics difficulty.

    ### Criterion 5: Multi-Step Recursive Rollout Validation
    We initialize the learned model from a true state $x_t$ and unroll it recursively over $H$ steps using true recorded controls:
    $$e_{t, k} = \|\hat{x}_{t+k} - x_{t+k}\|_2, \qquad E_H = \max_{1 \le k \le H} e_{t, k}$$
    alongside the maximum rollout support violation:
    $$Q_H = \max_{0 \le k < H} q(\hat{x}_{t+k}, u_{t+k})$$
    - **Desired ("Good")**: Positive correlation ($r > 0$) between $Q_H$ and $E_H$. When the optimizer proposes a trajectory with high $Q_H$, it should strongly indicate that the trajectory will diverge.
    """)
    return


@app.cell
def _(
    binned_prediction_error,
    cal_trajs,
    evaluate_prediction_errors,
    horizon,
    mo,
    model,
    n_u_val,
    n_y_val,
    np,
    ood_index,
    plt,
):
    q_1step, e_1step, q_max_r, e_max_r = evaluate_prediction_errors(
        model,
        ood_index,
        cal_trajs,
        horizon=horizon,
        n_y=n_y_val,
        n_u=n_u_val,
        stride=max(1, horizon // 6),
    )

    bins_summary = binned_prediction_error(q_1step, e_1step)

    fig_err, (ax_err1, ax_err2) = plt.subplots(1, 2, figsize=(12, 4.8))

    # Criterion 4: Bar chart with color progression indicating severity
    labels = [b["bin_label"] for b in bins_summary]
    means = [b["mean_error"] for b in bins_summary]
    counts = [b["count"] for b in bins_summary]
    bar_colors = ["#2ca02c", "#74c476", "#bcbd22", "#ffbb78", "#ff7f0e", "#d62728"]

    ax_err1.bar(labels, means, color=bar_colors[: len(labels)], alpha=0.85, edgecolor="black", lw=1.0)
    ax_err1.set_ylabel("Mean One-Step Error ||e_t||_2")
    ax_err1.set_xlabel("ID Calibration Percentile Bin")
    ax_err1.set_title("Criterion 4: One-Step Error vs. Support Percentile")
    ax_err1.grid(visible=True, linestyle=":", alpha=0.5, axis="y")

    # Add count annotations
    for idx_b, (m, c) in enumerate(zip(means, counts, strict=True)):
        if not np.isnan(m):
            ax_err1.text(idx_b, m * 1.02, f"n={c}", ha="center", va="bottom", fontsize=8.5, weight="bold")

    # Overlay desired monotonic trend annotation
    if not np.isnan(means[0]) and not np.isnan(means[-1]):
        ratio = means[-1] / max(means[0], 1e-6)
        ax_err1.text(
            0.05,
            0.90,
            f"Desired: Monotonic Escalation\nTail/Baseline Ratio = {ratio:.2f}x",
            transform=ax_err1.transAxes,
            fontsize=8.5,
            bbox={"boxstyle": "round,pad=0.4", "facecolor": "white", "edgecolor": "#2ca02c", "alpha": 0.9},
        )

    # Criterion 5: Multi-Step Rollout Error E_H vs Q_H
    ax_err2.axhspan(
        0,
        float(np.median(e_max_r)) if len(e_max_r) else 1.0,
        0,
        0.5,
        color="#2ca02c",
        alpha=0.10,
        label="Desired Zone (Low Q_H, Low E_H)",
    )
    ax_err2.axhspan(
        float(np.median(e_max_r)) if len(e_max_r) else 1.0,
        float(np.max(e_max_r) * 1.05) if len(e_max_r) else 2.0,
        0,
        0.5,
        color="#d62728",
        alpha=0.10,
        label="Dangerous Miss (Low Q_H, High E_H)",
    )

    ax_err2.scatter(q_max_r, e_max_r, color="#1f77b4", alpha=0.7, edgecolors="none", s=32)
    ax_err2.set_xlabel("Maximum Rollout Support Violation Q_H")
    ax_err2.set_ylabel("Maximum Rollout Prediction Error E_H")
    ax_err2.set_title("Criterion 5: Multi-Step Rollout Error vs. Q_H")
    ax_err2.grid(visible=True, linestyle=":", alpha=0.5)

    if len(q_max_r) > 1 and float(np.std(q_max_r)) > 1e-6 and float(np.std(e_max_r)) > 1e-6:
        corr = float(np.corrcoef(q_max_r, e_max_r)[0, 1])
        # Best-fit trendline
        p_fit = np.polyfit(q_max_r, e_max_r, 1)
        x_trend = np.linspace(float(q_max_r.min()), float(q_max_r.max()), 50)
        ax_err2.plot(
            x_trend,
            np.polyval(p_fit, x_trend),
            color="#d95f02",
            lw=2.0,
            linestyle="--",
            label=f"Trendline (r = {corr:+.3f})",
        )
        ax_err2.legend(loc="upper left", frameon=True, fontsize=8)
    else:
        corr = float("nan")

    plt.tight_layout()

    # Markdown Table of Bins
    table_rows = "\n".join(
        f"| {b['bin_label']} | {b['count']:,} | {b['mean_error']:.4f} | {b['std_error']:.4f} | {b['median_error']:.4f} |"
        for b in bins_summary
    )
    corr_display = f"{corr:+.3f}" if not np.isnan(corr) else "N/A (constant Q_H)"
    table_md = f"""
    ### 🔬 Empirical Error Calibration Table

    | Percentile Range | Sample Count | Mean Error ($e_t$) | Std Error | Median Error |
    | :--- | :---: | :---: | :---: | :---: |
    {table_rows}

    > **Key Validation Findings**:
    > - **One-Step Predictive Validity (Criterion 4)**: As queries cross from typical in-distribution ($0\\text{{--}}50\\%$) to extreme tail support ($99\\text{{--}}100\\%$), mean dynamics prediction error shifts by a factor of **{means[-1] / max(means[0], 1e-6):.2f}x**.
    > - **Multi-Step Rollout Divergence (Criterion 5)**: The maximum support violation along recursive rollouts correlates with maximum divergence error at $r = \\mathbf{{{corr_display}}}$.
    """

    mo.vstack([mo.as_html(fig_err), mo.md(table_md)])
    return bins_summary, corr


@app.cell
def _(mo, n_decisions):
    # Step Scrubber for inspecting an individual rollout
    step_slider = mo.ui.slider(
        start=0,
        stop=max(0, n_decisions - 1),
        step=1,
        value=min(20, max(0, n_decisions - 1)),
        label="Inspect Decision Step",
    )
    mo.vstack(
        [
            mo.md("---"),
            mo.md("## 6. Interactive Rollout Support Inspector"),
            mo.md(
                "Inspect candidate control trajectories and their corresponding support percentile sequence for any decision step in the closed-loop run:"
            ),
            step_slider,
        ]
    )
    return (step_slider,)


@app.cell
def _(horizon, mo, mpc_percentiles, planned_u, plt, step_slider):
    sel_step = step_slider.value
    sel_q = mpc_percentiles[sel_step]
    sel_u = planned_u[sel_step]

    fig_rollout, (ax_u, ax_q) = plt.subplots(1, 2, figsize=(12, 4.2))

    # Control sequence
    for ch in range(sel_u.shape[1]):
        ax_u.step(range(horizon), sel_u[:, ch], where="post", label=f"Electrode {ch + 1}", lw=1.8)
    ax_u.set_xlabel("Lookahead Horizon Step k")
    ax_u.set_ylabel("Planned Current (mA)")
    ax_u.set_title(f"Decision Step {sel_step}: Receding-Horizon Control Plan")
    ax_u.legend(loc="upper right", frameon=True, fontsize=8.5)
    ax_u.grid(visible=True, linestyle=":", alpha=0.5)

    # Support percentile with desired vs violation zones
    ax_q.axhspan(0.0, 0.50, color="#2ca02c", alpha=0.10, label="Desired Operating Zone (q < 0.50)")
    ax_q.axhspan(0.50, 0.95, color="#bcbd22", alpha=0.08, label="Acceptable Mild Shift")
    ax_q.axhspan(0.95, 1.0, color="#d62728", alpha=0.12, label="Unsupported Zone (q >= 0.95)")

    ax_q.plot(range(horizon), sel_q, marker="o", color="#d95f02", lw=2.2, ms=5, label="Rollout Support q_k")
    ax_q.axhline(0.50, color="#2ca02c", linestyle="--", lw=1.2, label="Desired Baseline (q ≈ 0.50)")
    ax_q.axhline(0.95, color="#ff7f0e", linestyle=":", lw=1.5, label="95% Threshold")
    ax_q.axhline(0.99, color="#d62728", linestyle=":", lw=1.5, label="99% Threshold")

    ax_q.set_xlabel("Lookahead Horizon Step k")
    ax_q.set_ylabel("Support Percentile q_k")
    ax_q.set_ylim(-0.02, 1.04)
    ax_q.set_title(f"Decision Step {sel_step}: Support Profile Along Rollout")
    ax_q.legend(loc="lower right", frameon=True, fontsize=8)
    ax_q.grid(visible=True, linestyle=":", alpha=0.5)

    plt.tight_layout()

    # Step diagnosis
    is_safe = float(sel_q.max()) < 0.95
    status_label = "✅ **Supported (Safe)**" if is_safe else "⚠️ **Unsupported Extrapolation Warning**"

    info_md = f"""
    > **Decision Step {sel_step} Assessment**: {status_label}
    > - Maximum support violation: $Q_\\text{{max}} = \\mathbf{{{sel_q.max():.3f}}}$ (Knot $k={int(sel_q.argmax())}$)
    > - Mean support score: $Q_\\text{{mean}} = \\mathbf{{{sel_q.mean():.3f}}}$
    > - Starting knot percentile: $q_0 = \\mathbf{{{sel_q[0]:.3f}}}$, Terminal knot percentile: $q_{{{horizon - 1}}} = \\mathbf{{{sel_q[-1]:.3f}}}$
    """

    mo.vstack([mo.as_html(fig_rollout), mo.md(info_md)])
    return


@app.cell
def _(mo):
    mo.md(r"""
    ---
    ## 7. Closing the Loop: OOD Candidate States & Dataset Extension

    ### Active Data Aggregation via Branch Simulation
    When closed-loop MPC fails to contain epileptic activity (or operates near uncontained seizure dynamics),
    the dynamics model is queried in unsupported regions ($q \ge 0.95$). As outlined in Section 16 of `docs/mpc_ood_experiment.md` (*"Closing the Data-Collection Loop"*), these queries reveal regions of state-action space that are crucial to the controller but underrepresented in the training data.

    ### Option B Branching Strategy
    To expand training coverage:
    1. We identify **Candidate States** $(t^*, x_{t^*})$ where the realized knot 0 query is out-of-distribution ($q \ge q^*$).
    2. We branch new simulation rollouts starting from each candidate state using **Random Amplitude Schedule (RAS)** excitation.
    3. The simulation replays the recorded closed-loop control currents and biophysical state up to $t^*$, branches forward under RAS excitation for $T_\text{branch}$ seconds, and preserves a $T_\text{hist}$ preceding history buffer (absorbing STFT warm-up and model input lag).
    4. The generated `.npz` branch trajectories are added directly to the training dataset.
    """)
    return


@app.cell
def _(mo, resolved_train_dir):
    ood_threshold_slider = mo.ui.slider(
        start=0.80,
        stop=0.99,
        step=0.01,
        value=0.95,
        label="Candidate OOD Percentile Threshold (q*)",
    )

    branch_dur_slider = mo.ui.slider(
        start=1.0,
        stop=8.0,
        step=0.5,
        value=4.0,
        label="Branch RAS Duration (s)",
    )

    branch_hist_slider = mo.ui.slider(
        start=0.5,
        stop=4.0,
        step=0.5,
        value=2.0,
        label="Preceding History Buffer (s)",
    )

    ras_seeds_input = mo.ui.text(
        value="101, 102, 103",
        label="Branch RAS Excitation Seeds",
        placeholder="e.g. 101, 102, 103",
    )

    target_data_dir_input = mo.ui.text(
        value=str(resolved_train_dir),
        label="Target Training Dataset Directory to Extend",
        placeholder="e.g. data/experiment_excited_60ms/train",
        full_width=True,
    )

    extend_btn = mo.ui.run_button(
        label="Simulate RAS Branches & Extend Dataset",
        kind="warn",
    )

    mo.vstack(
        [
            mo.md("### Candidate State Discovery & Dataset Extension Settings"),
            mo.hstack([ood_threshold_slider, branch_dur_slider, branch_hist_slider], justify="start"),
            mo.hstack([ras_seeds_input, extend_btn], justify="start"),
            target_data_dir_input,
        ]
    )
    return (
        branch_dur_slider,
        branch_hist_slider,
        extend_btn,
        ood_threshold_slider,
        ras_seeds_input,
        target_data_dir_input,
    )


@app.cell
def _(
    mo,
    model,
    n_u_val,
    n_y_val,
    ood_index,
    ood_threshold_slider,
    run_dir,
    select_ood_candidate_states,
):
    found_candidates = select_ood_candidate_states(
        run_dir,
        ood_index=ood_index,
        threshold=ood_threshold_slider.value,
        min_interval_s=1.5,
        max_candidates=5,
        n_y=n_y_val,
        n_u=n_u_val,
        model=model,
    )

    if not found_candidates:
        cand_selector = mo.ui.dropdown(
            options={"None found": None},
            value=None,
            label="Candidate State Selector",
        )
        _cands_view = mo.callout(
            mo.md(
                f"No candidate states found exceeding $q \\ge {ood_threshold_slider.value:.2f}$ in `{run_dir.name}`. "
                "Try selecting an uncontained seizure run (e.g. `fast_linear_kw5_s7002` or `s7004`) or lowering the threshold."
            ),
            kind="info",
        )
    else:
        _opts = {
            f"Candidate #{i + 1}: t* = {c.t_star:.2f}s (Decision {c.decision_idx}, q = {c.ood_score:.4f})": i
            for i, c in enumerate(found_candidates)
        }
        _opts["All Found Candidates"] = -1
        cand_selector = mo.ui.dropdown(
            options=_opts,
            value=-1,
            label="Candidate(s) to Branch From",
        )

        _cand_table_rows = "\n".join(
            f"| Candidate {i + 1} | Decision #{c.decision_idx} | **`{c.t_star:.2f}s`** | **`{c.ood_score:.4f}`** | `{c.run_dir.name}` |"
            for i, c in enumerate(found_candidates)
        )
        _cands_view = mo.vstack(
            [
                mo.md(f"""
                #### Discovered Candidate States ($q \\ge {ood_threshold_slider.value:.2f}$):
                | Candidate | Knot 0 Decision Step | Timestamp ($t^*$) | OOD Score ($q$) | Source Run |
                | :--- | :---: | :---: | :---: | :--- |
                {_cand_table_rows}
                """),
                cand_selector,
            ]
        )

    mo.vstack([_cands_view])
    return cand_selector, found_candidates


@app.cell
def _(
    Path,
    branch_dur_slider,
    branch_hist_slider,
    cand_selector,
    extend_btn,
    extract_state_action_pairs,
    found_candidates,
    frame_aligned_controls,
    geom,
    load_trajectory,
    mo,
    n_u_val,
    n_y_val,
    np,
    ood_index,
    ras_seeds_input,
    reduce_trajectory_to_frames,
    simulate_ras_branch,
    target_data_dir_input,
):
    if not extend_btn.value:
        _branch_view = mo.md(
            "*(Click **Simulate RAS Branches & Extend Dataset** to run Option B branching and add trajectories.)*"
        )
    elif not found_candidates:
        _branch_view = mo.callout(
            mo.md("Cannot extend dataset: no candidate states found above threshold."), kind="danger"
        )
    else:
        try:
            _seeds = tuple(int(s.strip()) for s in ras_seeds_input.value.split(",") if s.strip())
        except ValueError:
            _seeds = (101, 102, 103)

        _sel_val = cand_selector.value
        if _sel_val is None or _sel_val == -1:
            _target_cands = found_candidates
        elif isinstance(_sel_val, int) and 0 <= _sel_val < len(found_candidates):
            _target_cands = [found_candidates[_sel_val]]
        else:
            _target_cands = found_candidates

        _dest_dir = Path(target_data_dir_input.value.strip())
        _dest_dir.mkdir(parents=True, exist_ok=True)

        _created_branches = []
        for _idx_c, _cand in enumerate(_target_cands):
            _paths = simulate_ras_branch(
                _cand,
                ras_seeds=_seeds,
                duration_s=branch_dur_slider.value,
                history_s=branch_hist_slider.value,
                output_dir=_dest_dir,
                amp=2.0,
                prefix=f"cand{_idx_c + 1}",
            )
            _created_branches.extend((_cand, _p) for _p in _paths)

        _rows = []
        for _cand, _b_path in _created_branches:
            with np.load(_b_path) as _d:
                _s_t = np.asarray(_d["sensor_0.t"], dtype=np.float64)
                _s_y = np.asarray(_d["sensor_0.y_mea"], dtype=np.float64)
                _rel_t_star = float(_d["metadata_relative_t_star"])

            _u_data, _y_data = load_trajectory(str(_b_path), None, downsample=200, dt=0.0001)
            _dur = float(_s_t[-1] - _s_t[0])

            _mask_pre = _s_t < _rel_t_star
            _mask_post = _s_t >= _rel_t_star
            _rms_pre = float(np.sqrt(np.mean(_s_y[_mask_pre] ** 2))) if np.any(_mask_pre) else 0.0
            _rms_post = float(np.sqrt(np.mean(_s_y[_mask_post] ** 2))) if np.any(_mask_post) else 0.0

            if geom is not None:
                _y_frames = reduce_trajectory_to_frames(_y_data, geom, fs=50.0)
                if _y_frames.ndim > 2:
                    _y_frames = _y_frames.reshape(len(_y_frames), -1)
                _u_frames = frame_aligned_controls(_u_data, geom, fs=50.0)[: len(_y_frames)]
            else:
                _y_frames = _y_data
                _u_frames = _u_data
            _min_len = min(len(_y_frames), len(_u_frames))
            _z_b, _ = extract_state_action_pairs(
                [(_u_frames[:_min_len], _y_frames[:_min_len])], n_y=n_y_val, n_u=n_u_val
            )
            _d_b = ood_index.compute_distances(_z_b)
            _q_b = ood_index.percentiles(_d_b)
            _max_q = float(np.max(_q_b)) if len(_q_b) > 0 else 0.0

            _rows.append(
                f"| `{_b_path.name}` | {_dur:.2f}s | {_rms_pre:.2f} mV | {_rms_post:.2f} mV | **{_max_q:.4f}** |"
            )

        _report_table = "\n".join(_rows)
        _branch_view = mo.vstack(
            [
                mo.callout(
                    mo.md(
                        f"**Dataset Extended Successfully!**\n\n"
                        f"Generated **{len(_created_branches)}** new Option B branch trajectories saved to `{_dest_dir}`. "
                        f"These trajectories are now ready for model retraining."
                    ),
                    kind="success",
                ),
                mo.md(f"""
                #### Branched Trajectory Electrophysiology & OOD Evaluation:
                | Branch Trajectory File | Total Duration | Pre-$t^*$ LFP RMS | Post-$t^*$ LFP RMS | Peak $q(z)$ |
                | :--- | :---: | :---: | :---: | :--- |
                {_report_table}
                """),
            ]
        )

    mo.vstack([_branch_view])
    return


@app.cell
def _(
    active_k,
    bins_summary,
    cal_distances,
    clinical_metrics,
    corr,
    cv_score,
    dim,
    drift_delta,
    e_realized,
    h_stats,
    horizon,
    mean_q_max,
    mean_q_mean,
    mo,
    mpc_distances_flat,
    mpc_percentiles,
    ood_index,
    p95_rate,
    p99_rate,
    print_ood_report,
    run_dir,
):
    if not mo.running_in_notebook():
        print_ood_report(
            {
                "mpc_distances_flat": mpc_distances_flat,
                "cal_distances": cal_distances,
                "p95_rate": p95_rate,
                "p99_rate": p99_rate,
                "cv_score": cv_score,
                "h_stats": h_stats,
                "drift_delta": drift_delta,
                "mean_q_max": mean_q_max,
                "mean_q_mean": mean_q_mean,
                "bins_summary": bins_summary,
                "corr": corr,
                "horizon": horizon,
                "dim": dim,
                "active_k": active_k,
                "ood_index": ood_index,
                "run_select": run_dir,
                "mpc_percentiles": mpc_percentiles,
                "e_realized": e_realized,
                "clinical_metrics": clinical_metrics,
            }
        )
    return


if __name__ == "__main__":
    app.run()
