dt: 0.010
downsample: 10
n_steps: 2000
D: 1000
free_params:
  - A
  - w_weights

data_file: "results/sysid_plant_excited/log.npz"

base_model:
  params:
    A: 3.25
    sigma: 0.0
  n_nodes: 10
  w_weights_scale: 0.0
  target_electrode: ["CP5", "T7", "Fp1", "O1"]
  sigma: 20.0
