"""Verification script for reading ROAST gamma matrix generated by MATLAB."""

from pathlib import Path
from typing import Any

import h5py
import numpy as np
from scipy.io import loadmat


def verify_roast_gamma(mat_path: str | Path) -> dict[str, Any]:
    """Load and validate the ROAST gamma matrix exported from MATLAB."""
    path = Path(mat_path)
    if not path.exists():
        msg = f"ROAST gamma file not found at: {path}"
        raise FileNotFoundError(msg)

    try:
        data = loadmat(path, squeeze_me=True)
        gamma = np.asarray(data["gamma"], dtype=np.float64)
    except (NotImplementedError, ValueError):
        with h5py.File(path, "r") as h5_file:
            gamma = np.asarray(h5_file["gamma"], dtype=np.float64)
            if gamma.ndim == 2 and gamma.shape[0] > gamma.shape[1]:  # noqa: PLR2004
                gamma = gamma.T

    print(f"Successfully loaded gamma matrix from {path}")
    print(f"Gamma shape: {gamma.shape}")

    if gamma.ndim == 1:
        gamma = gamma[None, :]

    n_montages, n_regions = gamma.shape
    print(f"Number of montages: {n_montages}, Number of regions: {n_regions}")
    print(f"Gamma range: [{gamma.min():.4f}, {gamma.max():.4f}]")

    return {"gamma": gamma, "n_montages": n_montages, "n_regions": n_regions}


if __name__ == "__main__":
    test_file = Path("data/roast_gamma.mat")
    if test_file.exists():
        verify_roast_gamma(test_file)
    else:
        print(f"Info: {test_file} does not exist yet. Run generate_roast_gamma in MATLAB to create it.")
