experiments:
- t_end: 50.0
  dynamics:
    class_path: neuro.jansen_rit.JansenRitDynamics
    dt: 0.0001
    seed: 1023
    initial_state: rest
    connectome:
      speed: 50.0
      K: 0.60
    params:
      sigma: 280.0
      A:
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.6
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.6
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.6
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.25
      - 3.4
      - 3.25
      - 3.25
      - 3.4
      - 3.25
      - 3.25
      - 3.25
  reference:
    class_path: simulate.reference.StepReference
    dt: 0.0001
    step_value: 0.0
  sensors:
    class_path: simulate.sensor.GaussianSensor
    dt: 0.0001
    std_dev: 0.0
    measurement:
      class_path: neuro.eeg.EEGMeasurement
  estimator:
    class_path: simulate.estimator.IdentityEstimator
    dt: 0.0001
  controller:
    class_path: neuro.control.ZeroController
    dt: 0.0001
    n_u: 1
- dynamics:
    seed: 1024
- dynamics:
    seed: 1025
- dynamics:
    seed: 1026
- dynamics:
    seed: 1027
- dynamics:
    seed: 1028
- dynamics:
    seed: 1029
- dynamics:
    seed: 1030
- dynamics:
    seed: 1031
- dynamics:
    seed: 1032
- dynamics:
    seed: 1033
- dynamics:
    seed: 1034
- dynamics:
    seed: 1035
- dynamics:
    seed: 1036
- dynamics:
    seed: 1037
- dynamics:
    seed: 1038
- dynamics:
    seed: 1039
- dynamics:
    seed: 1040
- dynamics:
    seed: 1041
- dynamics:
    seed: 1042
- dynamics:
    seed: 1043
- dynamics:
    seed: 1044
- dynamics:
    seed: 1045
- dynamics:
    seed: 1046
- dynamics:
    seed: 1047
- dynamics:
    seed: 1048
- dynamics:
    seed: 1049
- dynamics:
    seed: 1050
- dynamics:
    seed: 1051
- dynamics:
    seed: 1052
- dynamics:
    seed: 1053
- dynamics:
    seed: 1054
- dynamics:
    seed: 1055
- dynamics:
    seed: 1056
- dynamics:
    seed: 1057
- dynamics:
    seed: 1058
- dynamics:
    seed: 1059
- dynamics:
    seed: 1060
- dynamics:
    seed: 1061
- dynamics:
    seed: 1062
- dynamics:
    seed: 1063
- dynamics:
    seed: 1064
- dynamics:
    seed: 1065
- dynamics:
    seed: 1066
- dynamics:
    seed: 1067
- dynamics:
    seed: 1068
- dynamics:
    seed: 1069
- dynamics:
    seed: 1070
- dynamics:
    seed: 1071
- dynamics:
    seed: 1072
- dynamics:
    seed: 1073
- dynamics:
    seed: 1074
- dynamics:
    seed: 1075
- dynamics:
    seed: 1076
- dynamics:
    seed: 1077
- dynamics:
    seed: 1078
- dynamics:
    seed: 1079
- dynamics:
    seed: 1080
- dynamics:
    seed: 1081
- dynamics:
    seed: 1082
- dynamics:
    seed: 1083
- dynamics:
    seed: 1084
- dynamics:
    seed: 1085
- dynamics:
    seed: 1086
- dynamics:
    seed: 1087
- dynamics:
    seed: 1088
- dynamics:
    seed: 1089
- dynamics:
    seed: 1090
- dynamics:
    seed: 1091
- dynamics:
    seed: 1092
- dynamics:
    seed: 1093
- dynamics:
    seed: 1094
- dynamics:
    seed: 1095
- dynamics:
    seed: 1096
- dynamics:
    seed: 1097
- dynamics:
    seed: 1098
- dynamics:
    seed: 1099
- dynamics:
    seed: 1100
- dynamics:
    seed: 1101
- dynamics:
    seed: 1102
- dynamics:
    seed: 1103
- dynamics:
    seed: 1104
- dynamics:
    seed: 1105
- dynamics:
    seed: 1106
- dynamics:
    seed: 1107
- dynamics:
    seed: 1108
- dynamics:
    seed: 1109
- dynamics:
    seed: 1110
- dynamics:
    seed: 1111
- dynamics:
    seed: 1112
- dynamics:
    seed: 1113
- dynamics:
    seed: 1114
- dynamics:
    seed: 1115
- dynamics:
    seed: 1116
- dynamics:
    seed: 1117
- dynamics:
    seed: 1118
- dynamics:
    seed: 1119
- dynamics:
    seed: 1120
- dynamics:
    seed: 1121
- dynamics:
    seed: 1122
